### PR TITLE
limit angular to 1.4.x - until compatible with 1.5.x

### PR DESCRIPTION
**Pull request by the-james-burton**
Hi, I just tried this project but unfortunately it is broken out of the box. Details in https://github.com/johnpapa/generator-hottowel/issues/154. It doesn't seem to be happy with Angular 1.5.

Until you can bring it up to date, here is a trivial PR that will restrict it to Angular 1.4.x. This solution was from https://github.com/kmorey. This makes it build fine for me, although I've not done any more serious testing.

Hope that helps,
James

### CODE REVIEW

**Comment by johnpapa** [comment]
Instead of limiting, let's work on a fix. What broke? Please visit the issues and provide details.

thanks

**Comment by the-james-burton** [comment]
Hi John. I had the same error as the original issue raiser. If there have not been any commits then you should be able to recreate simply by using it to make a new project.

This PR will get it working right now for anyone that wants to use it. You can then make the upgrade to 1.5 as a different task in your own time. Judging by the other comments on #154 after my PR, the community may have already made progress toward a fix.

Regards, James

**Comment by johnpapa** [comment]
so the issue is the tests?

lets close this and work on that.

**Comment by the-james-burton** [comment]
Hi John, I'm not sure myself. All I know is that downgrading to angular 1.4.x makes it work. This PR just quantified the solution from @kmorey, which is useful if someone wants it to work right now, as I did.

Reading #154, it looks like you may be waiting for a PR from @nuKs (assuming that fixes this issue and also upgrades angular to 1.5). Until that PR is delivered, this generator-hottowel project may not work without the modifications in this PR.

If I were you, I would merge this PR to get it working now for newcomers and maybe change the subject of #154 to "upgrade to angular 1.5" or similar. Of course, I will leave that to your better judgement!

Regards, James

**Comment by the-james-burton** [comment]
Actually, you've got PR 160 from @nuKs, so if that works then you definitely don't need this PR.

Hope that make it clear.

**Pull request closed without merging**
