### PR TITLE
Fixes #21

### LINKED ISSUE #21: splash screen
Inside the function hideSplash() (shell.controller.js) there is a timeout of 1 sec with the intention of waiting 1 sec to see the splash screen. But if you change it to 20 sec. (20000) nothing change and the spash screen remains only few moments as before.
bye.

Marco

### LINKED ISSUE #25: Environment configuration separation
Hi,

I'm using several environments for projects, such as dev, QA, preprod and production. Each has its own backend api server and other settings that are specific for each environment.

Currently, the config value is set in the core config file. Since that file is minified with the rest of the app, it's hard to change the configuration of the app on the fly. Also, each deployment of the app overwrites the config, so it has to be set before build for each environment.

I think a solution similar to web.config of ASP.NET would be great here. A file that can be updated after the application is built and without having to rebuild the app for each environment. This way the config file can be set once for each environment.

I was thinking about either using a json file that would load during application start or creating a file with a module and a value that is not minified during the build and would remain referenced as is so it can be changed on the server and not redeployed every time.

The first solution is a bit problematic since we don't have access to $http during config and the second one I'm not sure how to implement due to the complexity of the build process. Can't quite figure out how to tell gulp to inject the file but not alter it in any way.

What do you think?

### PR DESCRIPTION
**Pull request by yevk**

### CODE REVIEW

**Comment by yevk** [comment]
Sorry, this should be '#21' instead of '#25'

**Comment by johnpapa** [comment]
If you move the splash to the shell, then it wont show at all until angular is loaded. The point of the splash is to show before angular is ready, and then turn off once it is ready.

Can you explain what you are trying to do?

**Comment by yevk** [comment]
I was trying to resolve #21, but missed the fact that the splash should show before Angular is ready.

This still leaves the hideSplash timeout in shell controller non functional. If you want to do more work there and keep the splash screen showing before you finish, it won't work.

**Comment by johnpapa** [comment]
sure. feel free to make a PR

**Pull request closed without merging**
