### PR TITLE
Adds gitignore to project generated

### PR DESCRIPTION
**Pull request by willbuck**
I'm not totally sure how I test this, would love some feedback, but from as best as I could tell this should accomplish the task of setting a user of this generator up with a base nodejs gitignore with some extras added to ignore .idea/ and bower_components/

I'd be more than happy to add other common ignore files for front-end projects, let me know what you think!

### CODE REVIEW

**Comment by johnpapa** [comment]
there is a lot in the gitignore. it should just be the bare stuff that everyone needs. no .idea for example.

**Comment by willbuck** [comment]
I can understand that John, though I kind of feel like why not include things many people would want in there? It isn't hurting anyone who isn't using a Jetbrains product to have it there, and if Visual Studio or emacs or other editors that are popularly used have files that are commonly not checked into repos, I'd have no issue with those being in there either. Perhaps that's just me though.

That said, I can totally respect wanting to keep it minimalistic. Would you agree on the bower_components though? I'd be happy to re-submit a PR with just bower_components added.

**Comment by johnpapa** [comment]
yes. bower, node, and .tmp could be added. go for it

**Comment by willbuck** [comment]
Hey John! I trimmed down the gitignore, let me know what you think!

**Pull request merged**
