### PR TITLE
font awesome css file added into gulp.config

### PR DESCRIPTION
**Pull request by tithi021**

### CODE REVIEW

**Comment by tithi021** [comment]
After downloading the projects font awesome not working properly, Just added font awesome into the gulp config file, now It's working fine.

**Comment by levkovych67** [comment]
pidar check your pulls

**Comment by bbodenmiller** [comment]
Isn't https://github.com/johnpapa/generator-hottowel/pull/176 a better solution?

**Comment by johnpapa** [comment]
merged #176

**Pull request closed without merging**
