### PR TITLE
Upgrade phantomjs for angular 1.5 compatibility

### PR DESCRIPTION
**Pull request by nuKs**

### CODE REVIEW

**Comment by nuKs** [comment]
Tests :
```bash
nuKs:hottowel-nuks$ gulp test
[14:10:21] Using gulpfile ~/Documents/_osimis/hottowel-nuks/gulpfile.js
[14:10:21] Starting 'vet'...
[14:10:21] Analyzing source with JSHint and JSCS
[14:10:22] Starting 'clean-code'...
[14:10:22] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[14:10:22] Finished 'clean-code' after 36 ms
[14:10:22] Starting 'templatecache'...
[14:10:22] Creating an AngularJS $templateCache
[14:10:23] Finished 'templatecache' after 482 ms
[14:10:24] Finished 'vet' after 2.97 s
[14:10:24] Starting 'test'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use 
  server = new Server(config, [done])
  server.start()
instead.
01 03 2016 14:10:25.545:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
01 03 2016 14:10:25.838:WARN [watcher]: Pattern "/Users/nuKs/Documents/_osimis/hottowel-nuks/src/client/tests/server-integration/**/*.spec.js" does not match any file.
01 03 2016 14:10:26.070:WARN [karma]: Port 9876 in use
01 03 2016 14:10:26.071:INFO [karma]: Karma v0.13.21 server started at http://localhost:9877/
01 03 2016 14:10:26.078:INFO [launcher]: Starting browser PhantomJS2
01 03 2016 14:10:27.220:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#LMUHID2YnmY_GOxjAAAA with id 41293740
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 39 of 39 SUCCESS (0.472 secs / 0.06 secs)

=============================== Coverage summary ===============================
Statements   : 85.92% ( 238/277 )
Branches     : 45.45% ( 20/44 )
Functions    : 83.87% ( 78/93 )
Lines        : 85.77% ( 235/274 )
================================================================================
[14:10:28] Karma completed
[14:10:28] Finished 'test' after 3.82 s
```

**Comment by nuKs** [comment]
```bash
nuKs:hottowel-nuks$ bower install --save angular angular-sanitize angular-ui-router angular-animate
bower angular#*                 cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#*               validate 1.5.0 against git://github.com/angular/bower-angular.git#*
bower angular-sanitize#*        cached git://github.com/angular/bower-angular-sanitize.git#1.5.0
bower angular-sanitize#*      validate 1.5.0 against git://github.com/angular/bower-angular-sanitize.git#*
bower angular-ui-router#*       cached git://github.com/angular-ui/angular-ui-router-bower.git#0.2.18
bower angular-ui-router#*     validate 0.2.18 against git://github.com/angular-ui/angular-ui-router-bower.git#*
bower angular-animate#*         cached git://github.com/angular/bower-angular-animate.git#1.5.0
bower angular-animate#*       validate 1.5.0 against git://github.com/angular/bower-angular-animate.git#*
bower angular#^1.4.5            cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.4.5          validate 1.5.0 against git://github.com/angular/bower-angular.git#^1.4.5
bower angular#1.5.0             cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#1.5.0           validate 1.5.0 against git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.2.25           cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.2.25         validate 1.5.0 against git://github.com/angular/bower-angular.git#^1.2.25
nuKs:hottowel-nuks$ gulp test
[14:12:03] Using gulpfile ~/Documents/_osimis/hottowel-nuks/gulpfile.js
[14:12:03] Starting 'vet'...
[14:12:03] Analyzing source with JSHint and JSCS
[14:12:04] Starting 'clean-code'...
[14:12:04] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[14:12:04] Finished 'clean-code' after 62 ms
[14:12:04] Starting 'templatecache'...
[14:12:04] Creating an AngularJS $templateCache
[14:12:06] Finished 'vet' after 3.28 s
[14:12:06] Finished 'templatecache' after 1.95 s
[14:12:06] Starting 'test'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use 
  server = new Server(config, [done])
  server.start()
instead.
01 03 2016 14:12:08.372:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
01 03 2016 14:12:08.984:WARN [watcher]: Pattern "/Users/nuKs/Documents/_osimis/hottowel-nuks/src/client/tests/server-integration/**/*.spec.js" does not match any file.
01 03 2016 14:12:09.659:WARN [karma]: Port 9876 in use
01 03 2016 14:12:09.660:INFO [karma]: Karma v0.13.21 server started at http://localhost:9877/
01 03 2016 14:12:09.666:INFO [launcher]: Starting browser PhantomJS2
01 03 2016 14:12:11.344:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#2on5SqJrf4PTK_HrAAAA with id 28440588
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 39 of 39 SUCCESS (0.917 secs / 0.071 secs)

=============================== Coverage summary ===============================
Statements   : 85.92% ( 238/277 )
Branches     : 45.45% ( 20/44 )
Functions    : 83.87% ( 78/93 )
Lines        : 85.77% ( 235/274 )
================================================================================
[14:12:13] Karma completed
[14:12:13] Finished 'test' after 6.88 s
```

**Comment by johnpapa** [comment]
did you test for A1.3 and A1.4 too?

**Comment by nuKs** [comment]
Nope, I do it right away.
By the way, the app source code is also compatible with angular 1.5 (tested).

**Comment by nuKs** [comment]
Test angular 1.3
nuKs:hottowel-nuks$ bower install --save angular#1.3 angular-sanitize#1.3 angular-animate#1.3
bower angular#1.3               cached git://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3             validate 1.3.20 against git://github.com/angular/bower-angular.git#1.3
bower angular-sanitize#1.3      cached git://github.com/angular/bower-angular-sanitize.git#1.3.20
bower angular-sanitize#1.3    validate 1.3.20 against git://github.com/angular/bower-angular-sanitize.git#1.3
bower angular-animate#1.3       cached git://github.com/angular/bower-angular-animate.git#1.3.20
bower angular-animate#1.3     validate 1.3.20 against git://github.com/angular/bower-angular-animate.git#1.3
bower angular-sanitize#^1.5.0   cached git://github.com/angular/bower-angular-sanitize.git#1.5.0
bower angular-sanitize#^1.5.0 validate 1.5.0 against git://github.com/angular/bower-angular-sanitize.git#^1.5.0
bower angular-ui-router#^0.2.18 cached git://github.com/angular-ui/angular-ui-router-bower.git#0.2.18
bower angular-ui-router#^0.2.18         validate 0.2.18 against git://github.com/angular-ui/angular-ui-router-bower.git#^0.2.18
bower angular-animate#^1.5.0              cached git://github.com/angular/bower-angular-animate.git#1.5.0
bower angular-animate#^1.5.0            validate 1.5.0 against git://github.com/angular/bower-angular-animate.git#^1.5.0
bower angular#1.3.20                      cached git://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3.20                    validate 1.3.20 against git://github.com/angular/bower-angular.git#1.3.20
bower angular#^1.5.0                      cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.5.0                    validate 1.5.0 against git://github.com/angular/bower-angular.git#^1.5.0
bower angular#^1.2.25                     cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.2.25                   validate 1.5.0 against git://github.com/angular/bower-angular.git#^1.2.25

Unable to find a suitable version for angular, please choose one:
    1) angular#1.3.20 which resolved to 1.3.20 and is required by angular-animate#1.3.20, angular-sanitize#1.3.20
    2) angular#1.3 which resolved to 1.3.20
    3) angular#1.5.0 which resolved to 1.5.0 and is required by angular-animate#1.5.0, angular-sanitize#1.5.0
    4) angular#>=1.3.8 which resolved to 1.5.0 and is required by bardjs#0.1.8
    5) angular#^1.0.8 which resolved to 1.5.0 and is required by angular-ui-router#0.2.18
    6) angular#^1.5.0 which resolved to 1.5.0 and is required by hottowel-nuks
    7) angular#^1.2.25 which resolved to 1.5.0 and is required by extras.angular.plus#0.9.3

Prefix the choice with ! to persist it to bower.json

? Answer 1

Unable to find a suitable version for angular-sanitize, please choose one:
    1) angular-sanitize#1.3 which resolved to 1.3.20
    2) angular-sanitize#^1.5.0 which resolved to 1.5.0 and is required by hottowel-nuks

Prefix the choice with ! to persist it to bower.json

? Answer 1

Unable to find a suitable version for angular-animate, please choose one:
    1) angular-animate#1.3 which resolved to 1.3.20
    2) angular-animate#^1.5.0 which resolved to 1.5.0 and is required by hottowel-nuks

Prefix the choice with ! to persist it to bower.json

? Answer 1
bower angular#1.3.20                     install angular#1.3.20
bower angular-ui-router#^0.2.18          install angular-ui-router#0.2.18
bower angular-sanitize#1.3               install angular-sanitize#1.3.20
bower angular-animate#1.3                install angular-animate#1.3.20
bower                                postinstall gulp wiredep
bower                                postinstall [14:18:33] 
bower                                postinstall Using gulpfile ~/Documents/_osimis/hottowel-nuks/gulpfile.js
bower                                postinstall [14:18:33] 
bower                                postinstall Starting 'wiredep'...
bower                                postinstall [14:18:33] 
bower                                postinstall Wiring the bower dependencies into the html
bower                                postinstall [14:18:33] 
bower                                postinstall gulp-inject 27 files into index.html.
bower                                postinstall [14:18:33] Finished 'wiredep' after 198 ms

angular#1.3.20 bower_components/angular

angular-ui-router#0.2.18 bower_components/angular-ui-router
└── angular#1.3.20

angular-sanitize#1.3.20 bower_components/angular-sanitize
└── angular#1.3.20

angular-animate#1.3.20 bower_components/angular-animate
└── angular#1.3.20
nuKs:hottowel-nuks$ gulp test
[14:19:46] Using gulpfile ~/Documents/_osimis/hottowel-nuks/gulpfile.js
[14:19:46] Starting 'vet'...
[14:19:46] Analyzing source with JSHint and JSCS
[14:19:47] Starting 'clean-code'...
[14:19:47] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[14:19:47] Finished 'clean-code' after 61 ms
[14:19:47] Starting 'templatecache'...
[14:19:47] Creating an AngularJS $templateCache
[14:19:47] Finished 'templatecache' after 610 ms
[14:19:48] Finished 'vet' after 2.48 s
[14:19:48] Starting 'test'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use 
  server = new Server(config, [done])
  server.start()
instead.
01 03 2016 14:19:49.268:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
01 03 2016 14:19:49.585:WARN [watcher]: Pattern "/Users/nuKs/Documents/_osimis/hottowel-nuks/src/client/tests/server-integration/**/*.spec.js" does not match any file.
01 03 2016 14:19:49.802:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
01 03 2016 14:19:49.807:INFO [launcher]: Starting browser PhantomJS2
01 03 2016 14:19:50.684:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#-U2UR5EaFcg0VqpcAAAA with id 89828663
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 39 of 39 SUCCESS (0.342 secs / 0.047 secs)

=============================== Coverage summary ===============================
Statements   : 85.92% ( 238/277 )
Branches     : 45.45% ( 20/44 )
Functions    : 83.87% ( 78/93 )
Lines        : 85.77% ( 235/274 )
================================================================================
[14:19:51] Karma completed
[14:19:51] Finished 'test' after 3.13 s

**Comment by nuKs** [comment]
Test Angular 1.4
nuKs:hottowel-nuks$ bower install --save angular#1.4 angular-sanitize#1.4 angular-animate#1.4
bower angular-sanitize#1.4  not-cached git://github.com/angular/bower-angular-sanitize.git#1.4
bower angular-sanitize#1.4     resolve git://github.com/angular/bower-angular-sanitize.git#1.4
bower angular-animate#1.4   not-cached git://github.com/angular/bower-angular-animate.git#1.4
bower angular-animate#1.4      resolve git://github.com/angular/bower-angular-animate.git#1.4
bower angular#1.4               cached git://github.com/angular/bower-angular.git#1.4.9
bower angular#1.4             validate 1.4.9 against git://github.com/angular/bower-angular.git#1.4
bower angular-sanitize#1.4    download https://github.com/angular/bower-angular-sanitize/archive/v1.4.9.tar.gz
bower angular-animate#1.4     download https://github.com/angular/bower-angular-animate/archive/v1.4.9.tar.gz
bower angular#1.3               cached git://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3             validate 1.3.20 against git://github.com/angular/bower-angular.git#1.3
bower angular#^1.2.25           cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.2.25         validate 1.5.0 against git://github.com/angular/bower-angular.git#^1.2.25
bower angular#^1.0.8            cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#^1.0.8          validate 1.5.0 against git://github.com/angular/bower-angular.git#^1.0.8
bower angular#1.5.0             cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#1.5.0           validate 1.5.0 against git://github.com/angular/bower-angular.git#1.5.0
bower angular#>=1.3.8           cached git://github.com/angular/bower-angular.git#1.5.0
bower angular#>=1.3.8         validate 1.5.0 against git://github.com/angular/bower-angular.git#>=1.3.8
bower angular-sanitize#1.4     extract archive.tar.gz
bower angular-sanitize#1.4    resolved git://github.com/angular/bower-angular-sanitize.git#1.4.9
bower angular-animate#1.4      extract archive.tar.gz
bower angular-animate#1.4     resolved git://github.com/angular/bower-angular-animate.git#1.4.9

Unable to find a suitable version for angular-sanitize, please choose one:
    1) angular-sanitize#1.3 which resolved to 1.3.20 and is required by hottowel-nuks
    2) angular-sanitize#1.4 which resolved to 1.4.9

Prefix the choice with ! to persist it to bower.json

? Answer 2

Unable to find a suitable version for angular, please choose one:
    1) angular#1.3.20 which resolved to 1.3.20 and is required by angular-animate#1.3.20, angular-sanitize#1.3.20
    2) angular#1.3 which resolved to 1.3.20 and is required by hottowel-nuks
    3) angular#1.4.9 which resolved to 1.4.9 and is required by angular-animate#1.4.9, angular-sanitize#1.4.9
    4) angular#1.4 which resolved to 1.4.9
    5) angular#^1.2.25 which resolved to 1.5.0 and is required by extras.angular.plus#0.9.3
    6) angular#^1.0.8 which resolved to 1.5.0 and is required by angular-ui-router#0.2.18
    7) angular#1.5.0 which resolved to 1.5.0 and is required by angular-mocks#1.5.0
    8) angular#>=1.3.8 which resolved to 1.5.0 and is required by bardjs#0.1.8

Prefix the choice with ! to persist it to bower.json

? Answer 3

Unable to find a suitable version for angular-animate, please choose one:
    1) angular-animate#1.3 which resolved to 1.3.20 and is required by hottowel-nuks
    2) angular-animate#1.4 which resolved to 1.4.9

Prefix the choice with ! to persist it to bower.json

? Answer 2
bower angular-sanitize#1.4     install angular-sanitize#1.4.9
bower angular#1.4.9            install angular#1.4.9
bower angular-animate#1.4      install angular-animate#1.4.9
bower                      postinstall gulp wiredep
bower                      postinstall [14:21:34] 
bower                      postinstall Using gulpfile ~/Documents/_osimis/hottowel-nuks/gulpfile.js
bower                      postinstall [14:21:34] 
bower                      postinstall Starting 'wiredep'...
bower                      postinstall [14:21:34] 
bower                      postinstall Wiring the bower dependencies into the html
bower                      postinstall [14:21:34] 
bower                      postinstall gulp-inject 27 files into index.html.
bower                      postinstall [14:21:34] 
bower                      postinstall Finished 'wiredep' after 211 ms

angular-sanitize#1.4.9 bower_components/angular-sanitize
└── angular#1.4.9

angular#1.4.9 bower_components/angular

angular-animate#1.4.9 bower_components/angular-animate
└── angular#1.4.9
nuKs:hottowel-nuks$ gulp test
[14:21:38] Using gulpfile ~/Documents/_osimis/hottowel-nuks/gulpfile.js
[14:21:38] Starting 'vet'...
[14:21:38] Analyzing source with JSHint and JSCS
[14:21:39] Starting 'clean-code'...
[14:21:39] Cleaning: ./.tmp/**/*.js,./build/js/**/*.js,./build/**/*.html
[14:21:39] Finished 'clean-code' after 58 ms
[14:21:39] Starting 'templatecache'...
[14:21:39] Creating an AngularJS $templateCache
[14:21:40] Finished 'templatecache' after 576 ms
[14:21:41] Finished 'vet' after 2.6 s
[14:21:41] Starting 'test'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use 
  server = new Server(config, [done])
  server.start()
instead.
01 03 2016 14:21:42.085:WARN [config]: "/" is proxied, you should probably change urlRoot to avoid conflicts
01 03 2016 14:21:42.418:WARN [watcher]: Pattern "/Users/nuKs/Documents/_osimis/hottowel-nuks/src/client/tests/server-integration/**/*.spec.js" does not match any file.
01 03 2016 14:21:42.647:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
01 03 2016 14:21:42.652:INFO [launcher]: Starting browser PhantomJS2
01 03 2016 14:21:43.569:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#avEp2kVlZqV1Et6LAAAA with id 63592598
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 39 of 39 SUCCESS (0.39 secs / 0.057 secs)

=============================== Coverage summary ===============================
Statements   : 85.92% ( 238/277 )
Branches     : 45.45% ( 20/44 )
Functions    : 83.87% ( 78/93 )
Lines        : 85.77% ( 235/274 )
================================================================================
[14:21:44] Karma completed
[14:21:44] Finished 'test' after 3.35 s

**Comment by johnpapa** [comment]
LGTM

**Pull request merged**
